### PR TITLE
Mbed improvement

### PR DESCRIPTION
**Pull request by hyvarka**
### Description

Test with refactoring

### Pull request type

[ ] Fix  
[x] Refactor  
[ ] New target  
[ ] Feature  
[ ] Breaking change

### CODE REVIEW

**Comment by makimat** [comment]
### Softagram Impact Report for pull/2

Worst SG risk:100 Total SG risk points:317

### :star: Dependency changes:

All changed elements and changed dependencies.
Changed dependencies - click for full size
Graph legend
*(click for full size)*

### :star: Impact in the codebase:

Changed files and their direct users. Heat map color of each file illustrates its number of external users.
Impacted files - click for full size
Graph legend
*(click for full size)*

### :mag: Softagram Risk Score:

* SG risk:100 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/lorastack/mac/LoRaMac.cpp
* SG risk:100 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/system/lorawan_data_structures.h
* SG risk:80 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/LoRaWANStack.cpp
* SG risk:19 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/lorastack/mac/LoRaMac.h

:bulb: [*Softagram Risk Score explained*](http://help.softagram.com/reference/softagram-risk-score-explained)

### :page_facing_up: Full report

* Permalink: [Full report for pull/2](https://df.softagram.com/dashboard/teams/0b48b26d-69e4-4da1-9c2e-0e9779afa922/projects/833c0cbd-ef01-4cf5-8ac1-7806fded0dfd/impact-reports/8d03ec81-3ef8-4eb0-b085-86362a1af7a9)

#
Softagram impact report is in Beta. Give us feedback at support@softagram.com

**Comment by makimat** [comment]
### Softagram Impact Report for pull/2

Worst SG risk:100 Total SG risk points:317

### :star: Dependency changes:

All changed elements and changed dependencies.
Changed dependencies - click for full size
Graph legend
*(click for full size)*

### :star: Impact in the codebase:

Changed files and their direct users. Heat map color of each file illustrates its number of external users.
Impacted files - click for full size
Graph legend
*(click for full size)*

### :mag: Softagram Risk Score:

* SG risk:100 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/lorastack/mac/LoRaMac.cpp
* SG risk:100 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/system/lorawan_data_structures.h
* SG risk:80 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/LoRaWANStack.cpp
* SG risk:19 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/lorastack/mac/LoRaMac.h

:bulb: [*Softagram Risk Score explained*](http://help.softagram.com/reference/softagram-risk-score-explained)

### :page_facing_up: Full report

* Permalink: [Full report for pull/2](https://df.softagram.com/dashboard/teams/0b48b26d-69e4-4da1-9c2e-0e9779afa922/projects/833c0cbd-ef01-4cf5-8ac1-7806fded0dfd/impact-reports/f742cda3-c244-4240-99a3-39ef91683869)

#
Softagram impact report is in Beta. Give us feedback at support@softagram.com

**Comment by makimat** [comment]
### Softagram Impact Report for pull/2

Worst SG risk:100 Total SG risk points:417

### :star: Dependency changes:

All changed elements and changed dependencies.
Changed dependencies - click for full size
Graph legend
*(click for full size)*

### :star: Impact in the codebase:

Changed files and their direct users. Heat map color of each file illustrates its number of external users.
Impacted files - click for full size
Graph legend
*(click for full size)*

### :mag: Softagram Risk Score:

* SG risk:100 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/lorastack/mac/LoRaMac.cpp
* SG risk:100 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/system/lorawan_data_structures.h
* SG risk:100 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/mbed.h
* SG risk:80 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/LoRaWANStack.cpp
* SG risk:19 /mbed-os-example-blinky/mbedosexampleblinky/mbed-os/features/lorawan/lorastack/mac/LoRaMac.h

:bulb: [*Softagram Risk Score explained*](http://help.softagram.com/reference/softagram-risk-score-explained)

### :page_facing_up: Full report

* Permalink: [Full report for pull/2](https://df.softagram.com/dashboard/teams/0b48b26d-69e4-4da1-9c2e-0e9779afa922/projects/833c0cbd-ef01-4cf5-8ac1-7806fded0dfd/impact-reports/d5d8890e-6c50-4b6e-a625-b542e35a7136)

#
Softagram impact report is in Beta. Give us feedback at support@softagram.com

**Comment by hyvarka** [comment]
### Softagram Impact Report for pull/2

Total SG risk points:419

[Full report for pull/2](http://localhost:5000/dashboard/teams/31a7c7d1-02cd-4e05-9b25-5c8a2272cabc/projects/c3b87106-abe3-499f-8f84-5aba244f694c/impact-reports/5e10365a-80df-4f36-9b9a-2b3a63d5a272)

**Comment by hyvarka** [comment]
### Softagram Impact Report for pull/2

Total SG risk points:419

[Full report](http://localhost:5000/dashboard/teams/31a7c7d1-02cd-4e05-9b25-5c8a2272cabc/projects/c3b87106-abe3-499f-8f84-5aba244f694c/impact-reports/d24475b5-3cae-4824-8ef2-d2ae0f6e6ffc)

**Comment by hyvarka** [comment]
### Softagram Impact Report for pull/2

Worst SG risk:100 Total SG risk points:419

[Full report](http://localhost:5000/dashboard/teams/31a7c7d1-02cd-4e05-9b25-5c8a2272cabc/projects/c3b87106-abe3-499f-8f84-5aba244f694c/impact-reports/6f80d89c-0a6a-47a9-9db3-71bb0127e1f2)

**Comment by hyvarka** [comment]
### Softagram Impact Report

Worst SG risk:100 Total SG risk points:419

[Full report](http://localhost:5000/dashboard/teams/31a7c7d1-02cd-4e05-9b25-5c8a2272cabc/projects/c3b87106-abe3-499f-8f84-5aba244f694c/impact-reports/0db0ee93-e9e0-42a9-8330-71bb709aac81)

**Comment by hyvarka** [comment]
### Softagram Impact Report

Total SG risk points:419
[Open full report in Softagram](http://localhost:5000/dashboard/teams/31a7c7d1-02cd-4e05-9b25-5c8a2272cabc/projects/c3b87106-abe3-499f-8f84-5aba244f694c/impact-reports/6eb61d34-bf6e-4a17-b0b1-33d1664bdc88)

**Comment by hyvarka** [comment]
### Softagram Impact Report

Total SG risk points:419
[Open full report in Softagram](http://localhost:5000/dashboard/teams/31a7c7d1-02cd-4e05-9b25-5c8a2272cabc/projects/c3b87106-abe3-499f-8f84-5aba244f694c/impact-reports/4d8d1867-5640-4616-9b4b-f800f0541ff9)

**Comment by hyvarka** [comment]
### Softagram Impact Report

Total SG risk points:419
[Open full report in Softagram](http://localhost:5000/dashboard/teams/31a7c7d1-02cd-4e05-9b25-5c8a2272cabc/projects/c3b87106-abe3-499f-8f84-5aba244f694c/impact-reports/daa7c956-8289-4dbe-bd38-12b31fd4bd3c)

**Comment by hyvarka** [comment]
### Softagram Impact Report for pull/2

Worst SG risk:100 Total SG risk points:419

### :star: Dependency changes:

All changed elements and changed dependencies.
Changed dependencies - click for full size
Graph legend
*(click for full size)*

### :star: Impact in the codebase:

Changed files and their direct users. Heat map color of each file illustrates its number of external users.
Impacted files - click for full size
Graph legend
*(click for full size)*

### :mag: Softagram Risk Score:

* SG risk:100 /mbed-os-example-blinky/mbed-os-example-blinky/mbed-os/features/lorawan/lorastack/mac/LoRaMac.cpp
* SG risk:100 /mbed-os-example-blinky/mbed-os-example-blinky/mbed-os/features/lorawan/system/lorawan_data_structures.h
* SG risk:100 /mbed-os-example-blinky/mbed-os-example-blinky/mbed-os/mbed.h
* SG risk:86 /mbed-os-example-blinky/mbed-os-example-blinky/mbed-os/features/lorawan/LoRaWANStack.cpp
* SG risk:23 /mbed-os-example-blinky/mbed-os-example-blinky/mbed-os/features/lorawan/lorastack/mac/LoRaMac.h

:bulb: [*Softagram Risk Score explained*](http://help.softagram.com/reference/softagram-risk-score-explained)

### :page_facing_up: Full report

* Permalink: [Full report for pull/2](http://localhost:5000/dashboard/teams/31a7c7d1-02cd-4e05-9b25-5c8a2272cabc/projects/c3b87106-abe3-499f-8f84-5aba244f694c/impact-reports/16fcd01d-2e19-4e54-a58f-2814a438b913)

#
Softagram impact report is in Beta. Give us feedback at support@softagram.com

**Pull request closed without merging**
